name: Warehouse Maven Build

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file warehouse/pom.xml
        working-directory: warehouse

  publish-job:
    runs-on: ubuntu-latest
    needs: build_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Tests and Verify
        run: mvn --batch-mode --update-snapshots verify
        working-directory: warehouse

      - name: Prepare Artifact for Upload
        run: mkdir staging && cp warehouse/target/*.jar staging

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
