name: Warehouse Maven Build

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package
        working-directory: MicroserviceWarehouse/warehouse

      - name: List files in target directory
        run: ls -R target
        working-directory: MicroserviceWarehouse/warehouse

  publish-job:
    runs-on: ubuntu-latest
    needs: build_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: List files in target directory
        run: ls -R target
        working-directory: MicroserviceWarehouse/warehouse

      - name: Prepare Artifact for Upload
        run: mkdir -p staging && cp target/*.jar staging
        working-directory: MicroserviceWarehouse/warehouse

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
