name: Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file MicroserviceWarehouse/warehouse/pom.xml

  publish-job:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Copy artifacts
        run: |
          mkdir -p staging
          # Verificar si se generó algún archivo JAR antes de copiar
          if [[ -f MicroserviceWarehouse/warehouse/target/*.jar ]]; then
            cp MicroserviceWarehouse/warehouse/target/*.jar staging
          else
            echo "No se encontraron archivos JAR en el directorio target. Verifica el proceso de build."
            exit 1
          fi
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
