name: Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file MicroserviceWarehouse/warehouse/pom.xml

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: List target directory
        run: ls -R MicroserviceWarehouse/warehouse/target

      - name: Copy JAR file to staging
        run: mkdir -p staging && cp MicroserviceWarehouse/warehouse/target/*.jar staging

      - name: Upload JAR file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: warehouse-jar
          path: staging/*.jar
