name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: List files in the current directory
      run: ls -al

    - name: Build with Gradle
      run: cd Warehouse/TheWarehouse && ./gradlew build

    - name: Run Unit Tests
      run: cd Warehouse/TheWarehouse && ./gradlew test


