name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x Warehouse/TheWarehouse/gradlew

    - name: Build with Gradle
      run: Warehouse/TheWarehouse/gradlew build

    - name: Run Unit Tests
      run: Warehouse/TheWarehouse/gradlew test

